# coding: utf-8

"""
    Translator Knowledge Beacon API

    This is the Translator Knowledge Beacon web service application programming interface (API).   # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: richard@starinformatics.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tkbeacon
from tkbeacon.models.beacon_knowledge_map_statement import BeaconKnowledgeMapStatement  # noqa: E501
from tkbeacon.rest import ApiException

class TestBeaconKnowledgeMapStatement(unittest.TestCase):
    """BeaconKnowledgeMapStatement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BeaconKnowledgeMapStatement
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tkbeacon.models.beacon_knowledge_map_statement.BeaconKnowledgeMapStatement()  # noqa: E501
        if include_optional :
            return BeaconKnowledgeMapStatement(
                subject = tkbeacon.models.beacon_knowledge_map_subject.BeaconKnowledgeMapSubject(
                    category = '0', 
                    prefixes = [
                        '0'
                        ], ), 
                predicate = tkbeacon.models.beacon_knowledge_map_predicate.BeaconKnowledgeMapPredicate(
                    edge_label = '0', 
                    relation = '0', 
                    negated = True, ), 
                object = tkbeacon.models.beacon_knowledge_map_object.BeaconKnowledgeMapObject(
                    category = '0', 
                    prefixes = [
                        '0'
                        ], ), 
                frequency = 56, 
                description = '0'
            )
        else :
            return BeaconKnowledgeMapStatement(
        )

    def testBeaconKnowledgeMapStatement(self):
        """Test BeaconKnowledgeMapStatement"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
